# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='audio.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61udio.proto\x1a\x0cnanopb.proto\"#\n\x0c\x61udioMessage\x12\x13\n\x04\x64\x61ta\x18\x01 \x03(\rB\x05\x92?\x02\x10<b\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_AUDIOMESSAGE = _descriptor.Descriptor(
  name='audioMessage',
  full_name='audioMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='audioMessage.data', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\020<'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['audioMessage'] = _AUDIOMESSAGE

audioMessage = _reflection.GeneratedProtocolMessageType('audioMessage', (_message.Message,), dict(
  DESCRIPTOR = _AUDIOMESSAGE,
  __module__ = 'audio_pb2'
  # @@protoc_insertion_point(class_scope:audioMessage)
  ))
_sym_db.RegisterMessage(audioMessage)


_AUDIOMESSAGE.fields_by_name['data'].has_options = True
_AUDIOMESSAGE.fields_by_name['data']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\020<'))
# @@protoc_insertion_point(module_scope)
