/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Sat Jan 28 14:05:20 2017. */

#include "audio.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t audioMessage_fields[2] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, audioMessage, data, data, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
